### ISSUE TITLE
Valid ranges for environmental variables

### ISSUE THREAD

**Issue by rafapoyatos** [sapfluxnet/sapfluxnetQC1#23]
I have a found a source with global extreme weather records we can use to specify valid ranges for environmental variables http://journals.ametsoc.org/doi/pdf/10.1175/BAMS-88-6-853

I found this paper cited in here: http://journals.ametsoc.org/doi/10.1175/JAMC-D-15-0126.1
They analyse Ameriflux data and they set ranges according to US values:
- [ ] Temperature (-62.22 ºC, 56.67 ºC)
- [ ]  Wind speed (45 ms-1, max gust in Cerveny is 103 ms-1) 

Other range-based QC actions we can apply:
- [ ] Set relative humidity to 0-100 % . 
- [ ] Set negative values of global radiation/PAR to 0. Maxima can be dealt with when we calculate extraterrestrial or clear-sky radiation.

**Comment by MalditoBarbudo** [comment]
This issue corresponds now to sapfluxnetQC2
