### ISSUE TITLE
qc_set_timezone

### ISSUE THREAD

**Issue by vflo** [sapfluxnet/sapfluxnetQC1#32]
Fails when there is no TIMEZONE -> we need a check with an informative error

**Comment by MalditoBarbudo** [comment]
To fix this, a check must be added to **`qc_get_timezone`** function to ensure that if the timezone is not provided by the contributor (*NA* or *NULL*) an informative error is raised.

**Comment by MalditoBarbudo** [comment]
Fixed and tested in the `fix_issue_32` branch (see 5e4b4c675a100155f7cfdaafd6b97cb015de060b)

**Comment by MalditoBarbudo** [comment]
Fix reached the devel branch, closing now
