### ISSUE TITLE
Plotting environmental responses

### ISSUE THREAD

**Issue by rafapoyatos** [sapfluxnet/sapfluxnetQC1#42]
@MalditoBarbudo 
Is there an easy way to implement plotting of environmental responses, by plant, within a dataset? (e.g. J vs vpd). The response could be visualised using some smoothing function...

**Comment by MalditoBarbudo** [comment]
Working on it

**Comment by MalditoBarbudo** [comment]
Now there is a function clalled `vis_environmental_responses` to produce this kind of plot.
See `?vis_environmental_responses` to see how it works
